# Generated by Django 3.1.3 on 2020-11-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
