# Generated by Django 3.1.3 on 2020-11-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201125_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='formresponse',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.formresponse'),
        ),
    ]
